stages:
  - build
  - deploy
  
build_job:
  image: node:alpine
  stage: build
  before_script:
    - echo "Installing NPM Dependencies and building React app"
  script:
    - npm install
    - npm run build
  after_script:
    - echo "Installation and build successfull"
  cache:
    key: install-cache
    paths:
      - node_modules/
  artifacts:
    paths:
      - build/
  
deploy_job:
  image: google/cloud-sdk:alpine
  stage: deploy
  dependencies: 
    - build_job
  before_script:
  - "ServiceName=opvizorfrontend"
  - "echo $ServiceName"
  - |
    cat <<EOF >> app.yaml
    runtime: nodejs14
    service: $ServiceName
    handlers:
    # Serve all static files with url ending with a file extension
    - url: /(.*\..+)$
      static_files: build/\1
      upload: build/(.*\..+)$
    # Catch all handler to index.html
    - url: /.*
      static_files: build/index.html
      upload: build/index.html
    EOF
  - "cat app.yaml"
  - echo $SERVICE_ACCOUNT > ${CI_PIPELINE_ID}.json
  script:
  - gcloud auth activate-service-account --key-file $CI_PIPELINE_ID.json
  - gcloud --project hu18-groupa-angular app deploy --version v1
  - url=$(gcloud app services browse $ServiceName --no-launch-browser --project hu18-groupa-angular)
  - echo $url
  after_script:
  - rm $CI_PIPELINE_ID.json
